<section>
    <p>Hahaha, I'm still alive! <del>It hasn't even been two weeks and</del> <ins>OK, it's been two weeks and it took me forever to write this because I just kept coming up with new things to put in the post</ins> the third post is here! Anyways, this post is borne out of some recent feelings I've been having about the past few months of my life, so enjoy my unhinged, unedited ramblings (<i>ok I'm not really that unhinged, it's exaggeration for effect you see</i>)</p>
</section>

<section>
    <h3>how i made a blog</h3>
    <p>I initially started this site as a web dev project in 2024, which is a couple of years after I got out of college. I hadn't really had any success applying to jobs, so I wanted to take a shot at doing a personal project. When thinking about what kind of website I wanted to make, my first thought was to make a blog, since that's what all the cool people I followed online had. I had a couple math talks lying around that I wanted to put up for safekeeping, and lofty dreams of making my own games and putting those up here as well, so I set to work.</p>

    <p>As with most things I do, the hardest part is starting. My philosophy was that I wanted to do it from scratch (<a href="https://www.youtube.com/watch?v=Qf56xUKbx24">this video</a> largely sums up why I like this idea) and have full creative control over my website, which led me to VPS (Virtual Private Server) hosting. It gives you full control over the server you rent out and is cheaper, at the cost of being more complicated to set up and requiring more technical know-how. I ended up talking to a coder friend of mine and they recommended the platform DigitalOcean for VPS hosting, so I went ahead and did that.</p>

    <p>One $7.80/month subscription later, and I am the proud owner of a DigitalOcean "droplet", as they call them. I had no idea how to set one up, but that's what search engines are for. Thank you, <a href="https://www.digitalocean.com/community/tutorials/how-to-install-lamp-stack-on-ubuntu">DigitalOcean tutorials</a>. I had some experience doing a <a href="https://en.wikipedia.org/wiki/LAMP_(software_bundle)">LAMP stack</a> for my college web dev class, so that's what I used for the backend.</p>

    <p>The next step was getting a domain name. The same coding friend I talked to about VPS hosting also recommended Namecheap for purchasing a domain name, and I ended up going with "hexlab" for the name of the website, <a href="https://polytropica.xyz/blog/post.php?id=2">a decision I ended up regretting in my other blog post</a>, but this isn't about that. Another $10/year later, I have a domain name! After some manual setup of the <a href="https://easydmarc.com/blog/top-8-most-common-types-of-dns-records/">A and AAAA records</a>, I have a real domain name that points to my server.</p>

    <p>After that, the rest was re-learning all the aspects of web development I had forgotten. There's HTML, CSS, PHP, and SQL, as well as some stuff I didn't know how to do previously, like configuring Apache. It took me around a month of work to get this site from "hello world" to my first blog post about hexagons. There's been a tremendous amount of work behind the scenes after that first month, but the site has not evolved design-wise too much past that first month.</p>

    <p>Then, my progress on the site died in the middle of trying to make the backend work, <a href="https://polytropica.xyz/blog/post.php?id=2">as I conveniently talked about before in that one other blog post</a>. I dragged this project out of the unfinished pile back into the light, and now we are here.</p>
</section>

<section>
    <h3>why bother doing all this?</h3>
    <p>After thinking about it, I realized that the way I've done this is really rather bizarre.</p>

    <ul>
        <li>If I wanted to make a blog website, I could've just used WordPress and started writing immediately instead of trying to implement all of WordPress's functionality from scratch.</li>
        <li>If I wanted a resume builder, I didn't <i>have</i> to make a blog website. I could've made any other kind of website, like a portfolio or a video game. Heck, it didn't even have to be a website!</li>
    </ul>

    <p>Yet I chose to specifically do <i>this</i>, in the hardest way possible. Now that I get out a bit more often, I go to a lot of meetups and tell people about my website. Everyone then asks what framework I used, and they are then bewildered when I tell them "It's just PHP". It's kind of funny, actually.</p>

    <p>There's a couple pieces to this puzzle and I think one of those pieces was my main design inspiration, <a href="https://msx.horse">em essex/halley labs's personal website</a>. They make great music, but that's beside the point. Not only does it have this great coding/terminal aesthetic, it just feels very raw and real and personal in a way I wanted to replicate. It's even coded by scratch in PHP, with Notepad++ of all things (note: I did not code this website in Notepad++, I use an IDE like a normal person). Looking at this again made me realize I wanted an "everything" website of my own, that's "really mine" as em puts it in their website.</p>

    <p>With this perspective, it makes a lot more sense why I was so committed to this idea. It's a lot of work to set up something like this from scratch, but I don't want just another WordPress or Substack or whatever people are using these days. I want something that's <i>uniquely mine</i> that gets to show off what I want in my website, and that means I don't really care if that means it took me 16 months to make a second post. I'm sort of sad that it took this long for me to get here, but now that I <i>am</i> here, I don't want it any other way. Not only do I understand so many things about running a web server that I didn't know before, it's also very easy for me to change something if I don't like it or I found something fancy, since I wrote it all myself. There's no way in hell this is the correct approach for everyone, but I think this is the right way forward.</p>
</section>

<section>
    <h3>why i've been thinking about this recently</h3>
    <p>The second puzzle piece to why I'm doing this is something I realized recently, which is that I am not actually very good at expressing myself. There's a couple of reasons for this. One is that I have a lot of niche interests, and outside of those interests I really know nothing. This leads to not being able to find too many people I overlap with, since they're into, you know, <i>popular stuff</i>, and I am not. It's not that I hate popular things, it's just I'm really good at finding those small niche things that absolutely no one else is interested in, which is unfortunate in this particular circumstance.</p>

    <p>The second reason I'm terrible at expressing myself is that I'm <b><i>terrible</i></b> at talking to people. They're usually talking about stuff I have no knowledge about or don't care about, which makes it hard to contribute meaningfully. I can always try to talk about what I'm doing, but trying to find an opportunity in the conversation to talk about that is a nightmare. Even hanging out in inclusive spaces, I have a really tough time trying to get my word in. Usually the people who are already good at talking take up all the conversation space, and I just end up hanging out awkwardly waiting for them to talk about something I might be interested in. People have told me that I should just be more forceful, and they are almost certainly right, but this leads into the third reason.</p>

    <p>The third reason is that I'm terrible at coming up with responses on the spot. For some of my niche interests it's pretty easy for me to rant at length for however long I want (<i>that's the neurodivergence babyyyyy</i>) but outside of that my brain cannot come up with sensible responses in a reasonable time. In addition to not really being knowledgable about a lot of conversation topics, I don't relate to topics the same way others relate to them, so a lot of stock responses people have about common topics are just missing for me. I've had a lot of situations where the other person is talking about something both of us theoretically have in common, but all of my responses are stilted and awkward because I just can't relate to them in the way they're looking for.</p>

    <p>The end result of all this is that I don't really have a reliable outlet to express myself. The way I've described it to others is "drowning in air", but there's probably a better way to say it. You could argue that I should just get better at talking to people, but I think there are enough factors at play that it's not as simple as "just git gud lmao", and even then it takes time to make large improvements like that. All of this means I have lot of stories hanging out in my brain that are screaming to get out, but I just can't find the right time and place for them. This is where blogging comes in, as in this case it's sort of the perfect vehicle for self-expression. You can take as long as you want to think about how you want to say something, you don't have to worry about trying to interrupt the conversation at the right time, and you don't have to care about anyone actually being interested about what you have to say. You can just throw whatever you want to say on the internet, and people can randomly stumble across it and read it if they're interested. And even if no one finds it online, it's just nice to have a place you can link people to where you've already done all the hard work of trying to put your thoughts together.</p>

    <p>That being said, trying to start a blog actually creates a new problem. I may not be good at talking to people, but I'm also not good at writing. The way I'm currently writing this is just typing the first thing that comes to mind and hoping that people will want to read it, which feels like a terrible way to go about things. It is easier than trying to find the perfect person to info-dump onto for the aforementioned reasons, so we're running with it. I think I've been looking for this for a long time, and I'm very happy I finally have an outlet for it.</p>
</section>

<section>
    <h3>something's missing</h3>
    <p>Picture this. It's 5am. I've explained myself thoroughly. I want to get this post out already so I can go to sleep and show it off to people in the morning. Yet I still feel like we're missing the final piece of the puzzle. The problem is simple, really. <i>Why not just write a diary?</i> Sure I can't show off my diary to people, but I can still express myself. Why do I need to shove it online for the whole world to see?</p>

    <p>Something else I've realized recently is that people don't really care about what's going on in your life unless you make them aware. Everyone is so busy with their own lives, that it's hard to make time for other people's lives. I've been blessed with people who largely remember the things I talk about, but it still takes effort on my part to let them know what's going on in my life.</p>

    <p>The final piece of the puzzle is this. I can't remember where I heard it, but someone in a video asked, "When you die, what are you going to leave behind? What will you be remembered for?" Now I don't think I'm going to die any time soon (I'm in my late 20's) but thinking about this for too long <b><i>terrifies me</i></b>. I'm sure that the people around me will miss me, but there's <i>so many</i> unrealized thoughts and ideas running around in my head that I haven't gotten the chance to tell people about, or make into reality, or do really anything with. There is so much that I <i>want to be</i>, and my greatest fear is that no one will ever get to see that person.</p>

    <p><b><i>That's</i></b> why this "everything" site means so much to me. It's the place where I can get out the feelings I've been struggling to convey to other people in my life. It's the place I can tear apart the tangled web of my brain and figure out what makes it all tick. It's the place where my thoughts and feelings come first, and where people will come and listen to what I have to say. It's the digital proof of life that I existed and that something will be left behind when I'm gone. It's the place I'm finally putting together the "me" I want others to see so badly.</p>
</section>

<section>
    <h3>the puzzle is complete.</h3>
    <p>Welcome to my blog. I hope you'll stay a while.</p>
</section>